version: '3.8'

services:
  db:
    image: mariadb:10.10.2
    restart: always
    env_file:
      - local.env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mail
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - collections_dba

networks:
  collections_dba:
    name: "collections_dba"
    driver: bridge
